@api = http://localhost:3000/products

GET {{api}}

###
GET {{api}}/6


###
POST {{api}}
Content-Type: application/json

{
	"nombre": "Carcasa 5",
	"precio": 40000,
	"descripcion": "Novedosa carcasa",
	"id_proveedor": 1,
	"id_categoria": 1
}

###
DELETE {{api}}/6

###
PUT {{api}}/1
Content-Type: application/json

{
	"nombre": "Carcasa",
	"precio": 5000,
	"descripcion": "Novedosa carcasa",
	"id_proveedor": 1,
	"id_categoria": 1
}